export const CREATE_COURSE = 'CREATE_COURSE';
export const SEARCH_PRODUCT = 'SEARCH_PRODUCT';
export const GET_PRODUCT_ITEM = 'GET_PRODUCT_ITEM';
export const PRODUCT_API_ERROR = 'PRODUCT_API_ERROR';
export const SEARCHED_PRODUCT_TEXT = 'SEARCHED_PRODUCT_TEXT';
export const SET_RECCOMENDATION_PRODUCTS = 'SET_RECCOMENDATION_PRODUCTS'